FROM node:20.10.0-alpine3.18 AS BUILD_IMAGE

ARG  VITE_CURRENT_USER_API
ARG  VITE_REGISTER_USER_API
ARG  VITE_RECONFIRM_USER_API
ARG  VITE_LOG_OUT_USER_API
ARG  VITE_LOG_IN_USER_API
ARG  VITE_GET_INTERVIEW_BY_INTERVIEW_ID_API
ARG  VITE_CONFIRM_USER_API
ARG  VITE_RUN_ALGORITHM_API
ARG VITE_LOCAL_STORAGE_SECRET_KEY

ENV  VITE_CURRENT_USER_API=$VITE_CURRENT_USER_API
ENV  VITE_REGISTER_USER_API=$VITE_REGISTER_USER_API
ENV  VITE_RECONFIRM_USER_API=$VITE_RECONFIRM_USER_API
ENV  VITE_LOG_OUT_USER_API=$VITE_LOG_OUT_USER_API
ENV  VITE_LOG_IN_USER_API=$VITE_LOG_IN_USER_API
ENV  VITE_GET_INTERVIEW_BY_INTERVIEW_ID_API=$VITE_GET_INTERVIEW_BY_INTERVIEW_ID_API
ENV  VITE_CONFIRM_USER_API=$VITE_CONFIRM_USER_API
ENV  VITE_RUN_ALGORITHM_API=$VITE_RUN_ALGORITHM_API
ENV VITE_LOCAL_STORAGE_SECRET_KEY=$VITE_LOCAL_STORAGE_SECRET_KEY

WORKDIR /usr/app

# Copy package.json and package-lock.json (or npm.lock)
COPY . .
RUN npm cache clean --force
RUN npm install
RUN npm run build

# This build takes the build
FROM nginx:alpine

WORKDIR /usr/app

COPY --from=BUILD_IMAGE /usr/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]