version: '1'
services:
  pure:
    image: pure:1.0.0
    build: .
    ports:
      - "8080:80"
    environment:
      - "VITE_CURRENT_USER_API:${VITE_CURRENT_USER_API}"
      - "VITE_REGISTER_USER_API:${VITE_REGISTER_USER_API}"
      - "VITE_RECONFIRM_USER_API:${VITE_RECONFIRM_USER_API}"
      - "VITE_LOG_OUT_USER_API:${VITE_LOG_OUT_USER_API}"
      - "VITE_LOG_IN_USER_API:${VITE_LOG_IN_USER_API}"
      - "VITE_GET_INTERVIEW_BY_INTERVIEW_ID_API:${VITE_GET_INTERVIEW_BY_INTERVIEW_ID_API}"
      - "VITE_CONFIRM_USER_API:${VITE_CONFIRM_USER_API}"
      - "VITE_RUN_ALGORITHM_API:${VITE_RUN_ALGORITHM_API}"
      - "VITE_LOCAL_STORAGE_SECRET_KEY:${VITE_LOCAL_STORAGE_SECRET_KEY}"